// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "go-exercise/internal/domain"

	"github.com/stretchr/testify/mock"
)

// External is an autogenerated mock type for the External type
type External struct {
	mock.Mock
}

// GetTicker provides a mock function with given fields: pair
func (_m *External) GetTicker(pair domain.Pair) (domain.LTP, error) {
	ret := _m.Called(pair)

	var r0 domain.LTP
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Pair) (domain.LTP, error)); ok {
		return rf(pair)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(domain.LTP)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(error)
	}

	return r0, r1
}

// GetTickers provides a mock function with given fields: pairs
func (_m *External) GetTickers(pairs []domain.Pair) ([]domain.LTP, error) {
	ret := _m.Called(pairs)

	var r0 []domain.LTP
	var r1 error
	if rf, ok := ret.Get(0).(func([]domain.Pair) ([]domain.LTP, error)); ok {
		return rf(pairs)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.LTP)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(error)
	}

	return r0, r1
}
