// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "go-exercise/internal/domain"

	"github.com/stretchr/testify/mock"
)

// LTPService is an autogenerated mock type for the LTPService type
type LTPService struct {
	mock.Mock
}

// GetLTPs provides a mock function with given fields: pairsStr
func (_m *LTPService) GetLTPs(pairsStr string) ([]domain.LTP, error) {
	ret := _m.Called(pairsStr)

	var r0 []domain.LTP
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.LTP, error)); ok {
		return rf(pairsStr)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.LTP)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(error)
	}

	return r0, r1
}

