// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "go-exercise/internal/domain"

	"github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Clear provides a mock function with given fields:
func (_m *Repository) Clear() {
	_m.Called()
}

// GetLTP provides a mock function with given fields: pair
func (_m *Repository) GetLTP(pair domain.Pair) (*domain.CachedLTP, bool) {
	ret := _m.Called(pair)

	var r0 *domain.CachedLTP
	var r1 bool
	if rf, ok := ret.Get(0).(func(domain.Pair) (*domain.CachedLTP, bool)); ok {
		return rf(pair)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.CachedLTP)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SetLTP provides a mock function with given fields: pair, ltp
func (_m *Repository) SetLTP(pair domain.Pair, ltp domain.LTP) {
	_m.Called(pair, ltp)
}
